test:
  image: python:3.7
  script:
  - pip install -r requirements.txt
  - python manage.py test

staging:
  type: deploy
  script:
  - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git
  - git push -f heroku master
  only:
  - master
